stages:
  - validate
  - plan
  - apply
  - compliance

image:
  name: hashicorp/terraform:light
  entrypoint:
    - '/usr/bin/env'
    - 'PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin'

before_script:
  - export gcp_service_key=${gcp_service_key}
  - export gcp_service_id=${gcp_service_key}
  - rm -rf .terraform
  - terraform --version
  - terraform init

validate:
  stage: validate
  script:
    - terraform validate

plan:
  stage: plan
  script:
    - terraform plan -out "planfile"
  dependencies:
    - validate
  artifacts:
    paths:
      - planfile

apply:
  stage: apply
  script:
    - terraform apply -input=false "planfile"
  dependencies:
    - plan
  when: manual

compliance_check:
   stage: compliance
   script: 
     # - terraform plan -out plan.out
     # - terraform show -json plan.out > plan.out.json
     # - terraform-compliance -p plan.out.json -f compliance/
      - snyk iac test main.tf
   allow_failure: true
   when: manual

